FROM alpine:3.15.4
RUN apk --update add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del tzdata && \
    rm -rf /var/cache/apk/*
WORKDIR /
COPY bin/info-server-linux-amd64 .
USER 65532:65532
ENTRYPOINT ["/info-server-linux-amd64"]